# Generated by Django 3.2 on 2021-05-24 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20210524_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 8, 44, 35, 749412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
